<?php /* Smarty version 2.6.27, created on 2013-11-04 11:44:48
         compiled from m10_daylife_listing_dir.tpl */ ?>
<?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('modifier', 'nl2br', 'm10_daylife_listing_dir.tpl', 41, false),)), $this); ?>
<?php echo ''; ?><?php $_smarty_tpl_vars = $this->_tpl_vars;
$this->_smarty_include(array('smarty_include_tpl_file' => $this->_tpl_vars['headerfilename'], 'smarty_include_vars' => array()));
$this->_tpl_vars = $_smarty_tpl_vars;
unset($_smarty_tpl_vars);
 ?><?php echo '<div id="main_content"><br class="clearfloats" />'; ?><?php $this->assign('betweenListing', 'false'); ?><?php echo ''; ?><?php $_from = $this->_tpl_vars['MAIN_LISTINGS']; if (!is_array($_from) && !is_object($_from)) { settype($_from, 'array'); }if (count($_from)):
    foreach ($_from as $this->_tpl_vars['entry']):
?><?php echo ''; ?><?php if ($this->_tpl_vars['betweenListing'] == 'true'): ?><?php echo '<br clear="all" /><hr />'; ?><?php else: ?><?php echo ''; ?><?php $this->assign('betweenListing', 'true'); ?><?php echo ''; ?><?php endif; ?><?php echo '<div  class="listing_box"  '; ?><?php if ($this->_tpl_vars['entry']['list_more_url'] != ''): ?><?php echo ' onclick="location.href=\''; ?><?php echo $this->_tpl_vars['entry']['list_more_url']; ?><?php echo '\';"  style="cursor:pointer;" '; ?><?php endif; ?><?php echo '><div class="listinglogo"><a name="'; ?><?php echo $this->_tpl_vars['entry']['list_dirref']; ?><?php echo '" '; ?><?php if ($this->_tpl_vars['entry']['list_more_url'] != ''): ?><?php echo 'href="'; ?><?php echo $this->_tpl_vars['entry']['list_more_url']; ?><?php echo '"'; ?><?php endif; ?><?php echo '>'; ?><?php if ($this->_tpl_vars['entry']['list_src'] != ''): ?><?php echo '<img border="0" src="'; ?><?php echo $this->_tpl_vars['entry']['list_src']; ?><?php echo '" width="'; ?><?php echo $this->_tpl_vars['entry']['list_width']; ?><?php echo '" height="'; ?><?php echo $this->_tpl_vars['entry']['list_height']; ?><?php echo '" align="left">'; ?><?php else: ?><?php echo '<img border="0" src="/images/nopix.gif" width="100" height="100" align="left">'; ?><?php endif; ?><?php echo '</a></div><div class="listing_info"><div class="listmore">'; ?><?php if ($this->_tpl_vars['entry']['list_more_url'] != ''): ?><?php echo '<a href="'; ?><?php echo $this->_tpl_vars['entry']['list_more_url']; ?><?php echo '"><img border="0" height="25" width="25" src="/m/more.png"></a>&nbsp; &nbsp;'; ?><?php endif; ?><?php echo '</div><p class="listing_name">'; ?><?php echo $this->_tpl_vars['entry']['list_name']; ?><?php echo '</p><p class="listing_address">'; ?><?php echo $this->_tpl_vars['entry']['list_addr1']; ?><?php echo ''; ?><?php if ($this->_tpl_vars['entry']['list_addr2'] != ''): ?><?php echo ', '; ?><?php echo $this->_tpl_vars['entry']['list_addr2']; ?><?php echo ''; ?><?php endif; ?><?php echo ''; ?><?php if ($this->_tpl_vars['entry']['list_addr3'] != ''): ?><?php echo ', '; ?><?php echo $this->_tpl_vars['entry']['list_addr3']; ?><?php echo ''; ?><?php endif; ?><?php echo ''; ?><?php if ($this->_tpl_vars['entry']['list_phone'] != ''): ?><?php echo '<br /> Tel. '; ?><?php echo $this->_tpl_vars['entry']['list_phone']; ?><?php echo ''; ?><?php endif; ?><?php echo '</p><p>'; ?><?php echo ((is_array($_tmp=$this->_tpl_vars['entry']['list_descshort'])) ? $this->_run_mod_handler('nl2br', true, $_tmp) : smarty_modifier_nl2br($_tmp)); ?><?php echo '</p></div></div>'; ?><?php endforeach; endif; unset($_from); ?><?php echo ''; ?><?php $_from = $this->_tpl_vars['subcat']; if (!is_array($_from) && !is_object($_from)) { settype($_from, 'array'); }if (count($_from)):
    foreach ($_from as $this->_tpl_vars['sub']):
?><?php echo '<h2>'; ?><?php echo $this->_tpl_vars['sub']['subcat_name']; ?><?php echo '</h2><div>'; ?><?php if ($this->_tpl_vars['sub']['subcat_desc'] != ''): ?><?php echo ' <p style="padding-left: 10px;">'; ?><?php echo $this->_tpl_vars['sub']['subcat_desc']; ?><?php echo '</p>  <hr />'; ?><?php endif; ?><?php echo '</div>'; ?><?php $this->assign('betweenListing', 'false'); ?><?php echo ''; ?><?php $_from = $this->_tpl_vars['sub']['listing']; if (!is_array($_from) && !is_object($_from)) { settype($_from, 'array'); }if (count($_from)):
    foreach ($_from as $this->_tpl_vars['entry']):
?><?php echo ''; ?><?php if ($this->_tpl_vars['betweenListing'] == 'true'): ?><?php echo '<br clear="all" /><hr />'; ?><?php else: ?><?php echo ''; ?><?php $this->assign('betweenListing', 'true'); ?><?php echo ''; ?><?php endif; ?><?php echo '<div  class="sublisting_box" '; ?><?php if ($this->_tpl_vars['entry']['list_more_url'] != ''): ?><?php echo ' onclick="location.href=\''; ?><?php echo $this->_tpl_vars['entry']['list_more_url']; ?><?php echo '\';"  style="cursor:pointer;" '; ?><?php endif; ?><?php echo '><div class="listinglogo"><a name="'; ?><?php echo $this->_tpl_vars['entry']['list_dirref']; ?><?php echo '" '; ?><?php if ($this->_tpl_vars['entry']['list_more_url'] != ''): ?><?php echo 'href="'; ?><?php echo $this->_tpl_vars['entry']['list_more_url']; ?><?php echo '"'; ?><?php endif; ?><?php echo '>'; ?><?php if ($this->_tpl_vars['entry']['list_src'] != ''): ?><?php echo '<img border="0" src="'; ?><?php echo $this->_tpl_vars['entry']['list_src']; ?><?php echo '" width="'; ?><?php echo $this->_tpl_vars['entry']['list_width']; ?><?php echo '" height="'; ?><?php echo $this->_tpl_vars['entry']['list_height']; ?><?php echo '" align="left">'; ?><?php else: ?><?php echo '<img border="0" src="/images/nopix.gif" width="100" height="100" align="left">'; ?><?php endif; ?><?php echo '</a></div><div class="listing_info"><div class="listmore">'; ?><?php if ($this->_tpl_vars['entry']['list_more_url'] != ''): ?><?php echo '<a href="'; ?><?php echo $this->_tpl_vars['entry']['list_more_url']; ?><?php echo '"><img border="0" height="25" width="25" src="/m/more.png"></a>&nbsp; &nbsp;'; ?><?php endif; ?><?php echo '</div><p class="listing_name">'; ?><?php echo $this->_tpl_vars['entry']['list_name']; ?><?php echo '</p><p class="listing_address">'; ?><?php echo $this->_tpl_vars['entry']['list_addr1']; ?><?php echo ''; ?><?php if ($this->_tpl_vars['entry']['list_addr2'] != ''): ?><?php echo ', '; ?><?php echo $this->_tpl_vars['entry']['list_addr2']; ?><?php echo ''; ?><?php endif; ?><?php echo ''; ?><?php if ($this->_tpl_vars['entry']['list_addr3'] != ''): ?><?php echo ', '; ?><?php echo $this->_tpl_vars['entry']['list_addr3']; ?><?php echo ''; ?><?php endif; ?><?php echo ''; ?><?php if ($this->_tpl_vars['entry']['list_phone'] != ''): ?><?php echo '<br /> Tel. '; ?><?php echo $this->_tpl_vars['entry']['list_phone']; ?><?php echo ''; ?><?php endif; ?><?php echo '<br /></p><p>'; ?><?php echo ((is_array($_tmp=$this->_tpl_vars['entry']['list_descshort'])) ? $this->_run_mod_handler('nl2br', true, $_tmp) : smarty_modifier_nl2br($_tmp)); ?><?php echo '</p></div><br clear="left" /><br /></div>'; ?><?php endforeach; endif; unset($_from); ?><?php echo ''; ?><?php endforeach; endif; unset($_from); ?><?php echo '<br clear="all"  /><hr /></div>'; ?><?php $_smarty_tpl_vars = $this->_tpl_vars;
$this->_smarty_include(array('smarty_include_tpl_file' => "m10_footer.tpl", 'smarty_include_vars' => array()));
$this->_tpl_vars = $_smarty_tpl_vars;
unset($_smarty_tpl_vars);
 ?><?php echo ''; ?>