<?php /* Smarty version 2.6.26, created on 2012-10-10 10:35:40
         compiled from m10_lodging_info.tpl */ ?>
<?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'config_load', 'm10_lodging_info.tpl', 1, false),array('modifier', 'nl2br', 'm10_lodging_info.tpl', 35, false),)), $this); ?>
<?php echo ''; ?><?php echo smarty_function_config_load(array('file' => "ggv_search.conf"), $this);?><?php echo ''; ?><?php $_smarty_tpl_vars = $this->_tpl_vars;
$this->_smarty_include(array('smarty_include_tpl_file' => $this->_tpl_vars['headerfilename'], 'smarty_include_vars' => array()));
$this->_tpl_vars = $_smarty_tpl_vars;
unset($_smarty_tpl_vars);
 ?><?php echo '<div id="main_content"><div class="listing_box"><div class="listinglogo">'; ?><?php if ($this->_tpl_vars['lodging_logo_src'] != ''): ?><?php echo '<img border="0" src="../Listings/'; ?><?php echo $this->_tpl_vars['lodging_logo_src']; ?><?php echo '"  width="'; ?><?php echo $this->_tpl_vars['lodging_logo_width']; ?><?php echo '"  height="'; ?><?php echo $this->_tpl_vars['lodging_logo_height']; ?><?php echo '"  align="left">'; ?><?php else: ?><?php echo '&nbsp;'; ?><?php endif; ?><?php echo '</div><div class="listing_info"><p class="listing_name"  style="margin-top: 0px; padding-top: 0px;">'; ?><?php echo $this->_tpl_vars['hotel_name']; ?><?php echo '</p><p class="listing_address">'; ?><?php echo $this->_tpl_vars['lodging_addr1']; ?><?php echo ''; ?><?php if ($this->_tpl_vars['lodging_addr2'] != ''): ?><?php echo '<br /> '; ?><?php echo $this->_tpl_vars['lodging_addr2']; ?><?php echo ''; ?><?php endif; ?><?php echo ''; ?><?php if ($this->_tpl_vars['lodging_addr3'] != ''): ?><?php echo '<br /> '; ?><?php echo $this->_tpl_vars['lodging_addr3']; ?><?php echo ''; ?><?php endif; ?><?php echo ''; ?><?php if ($this->_tpl_vars['lodging_phone'] != ''): ?><?php echo '<br /> Tel. '; ?><?php echo $this->_tpl_vars['lodging_phone']; ?><?php echo ''; ?><?php endif; ?><?php echo '<br />'; ?><?php if ($this->_tpl_vars['lodging_link_url'] != ''): ?><?php echo '<br /><a class="listlink" href="'; ?><?php echo $this->_tpl_vars['lodging_link_url']; ?><?php echo '">website</a>&nbsp;&nbsp;'; ?><?php endif; ?><?php echo '</p>'; ?><?php if ($this->_tpl_vars['features'] != ""): ?><?php echo '<p><font face="Arial" color="#0099CC" size="1"><font size="2"><b><i>Property Features:</i></b></font> &nbsp;'; ?><?php echo $this->_tpl_vars['features']; ?><?php echo '</font></p>'; ?><?php endif; ?><?php echo '</div>'; ?><?php echo '</div>'; ?><?php echo '<div class="full_listing" style="margin: 0px; padding: 0px 10px 0px 10px;" ><p>'; ?><?php echo ((is_array($_tmp=$this->_tpl_vars['lodging_desclong'])) ? $this->_run_mod_handler('nl2br', true, $_tmp) : smarty_modifier_nl2br($_tmp)); ?><?php echo '</p></div>'; ?><?php echo ''; ?><?php if ($this->_tpl_vars['list_map'] != ''): ?><?php echo '<br /><H2>Location</H2><center><a href="'; ?><?php echo $this->_tpl_vars['list_mapbig']; ?><?php echo '"><img width="320" height="480" src="'; ?><?php echo $this->_tpl_vars['list_map']; ?><?php echo '" /></a></center><br />'; ?><?php endif; ?><?php echo '</div>'; ?><?php echo '</div>'; ?><?php echo ''; ?><?php $_smarty_tpl_vars = $this->_tpl_vars;
$this->_smarty_include(array('smarty_include_tpl_file' => "m10_footer.tpl", 'smarty_include_vars' => array()));
$this->_tpl_vars = $_smarty_tpl_vars;
unset($_smarty_tpl_vars);
 ?><?php echo ''; ?><?php echo ''; ?>