<?php /* Smarty version 2.6.27, created on 2013-11-04 11:17:54
         compiled from m10_listing_single.tpl */ ?>
<?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('modifier', 'nl2br', 'm10_listing_single.tpl', 53, false),)), $this); ?>
<?php echo ''; ?><?php $_smarty_tpl_vars = $this->_tpl_vars;
$this->_smarty_include(array('smarty_include_tpl_file' => $this->_tpl_vars['headerfilename'], 'smarty_include_vars' => array()));
$this->_tpl_vars = $_smarty_tpl_vars;
unset($_smarty_tpl_vars);
 ?><?php echo '<div id="main_content"><div id="Listing_full_content"><hr style="margin: 6px 0px 6px 0px;" /><div id="Listing_header"><div class="listinglogo">'; ?><?php if ($this->_tpl_vars['list_src'] != ''): ?><?php echo '<img border="0"src="'; ?><?php echo $this->_tpl_vars['list_src']; ?><?php echo '"width="'; ?><?php echo $this->_tpl_vars['list_width']; ?><?php echo '"height="'; ?><?php echo $this->_tpl_vars['list_height']; ?><?php echo '"align="left">'; ?><?php else: ?><?php echo '&nbsp;'; ?><?php endif; ?><?php echo '</div><div class="listing_info"><p class="listing_name">'; ?><?php echo $this->_tpl_vars['list_name']; ?><?php echo '</p><p class="listing_address">'; ?><?php echo $this->_tpl_vars['list_addr1']; ?><?php echo ''; ?><?php if ($this->_tpl_vars['list_addr2'] != ''): ?><?php echo '<br /> '; ?><?php echo $this->_tpl_vars['list_addr2']; ?><?php echo ''; ?><?php endif; ?><?php echo ''; ?><?php if ($this->_tpl_vars['list_addr3'] != ''): ?><?php echo '<br /> '; ?><?php echo $this->_tpl_vars['list_addr3']; ?><?php echo ''; ?><?php endif; ?><?php echo ''; ?><?php if ($this->_tpl_vars['list_phone'] != ''): ?><?php echo '<br /> Tel. '; ?><?php echo $this->_tpl_vars['list_phone']; ?><?php echo ''; ?><?php endif; ?><?php echo ''; ?><?php if ($this->_tpl_vars['list_cell'] != ''): ?><?php echo '<br /> Cel. '; ?><?php echo $this->_tpl_vars['list_cell']; ?><?php echo ''; ?><?php endif; ?><?php echo ''; ?><?php if ($this->_tpl_vars['list_intlphone'] != ''): ?><?php echo '<br /> US/Can. '; ?><?php echo $this->_tpl_vars['list_intlphone']; ?><?php echo ''; ?><?php endif; ?><?php echo '<br />'; ?><?php if ($this->_tpl_vars['list_url'] != ''): ?><?php echo '<a class="listlink" href="'; ?><?php echo $this->_tpl_vars['list_url']; ?><?php echo '">'; ?><?php echo $this->_tpl_vars['website']; ?><?php echo '</a>&nbsp;&nbsp;'; ?><?php endif; ?><?php echo ''; ?><?php if ($this->_tpl_vars['list_rows_cal'] != array ( )): ?><?php echo '<a class="listlink" href="#Calendar">'; ?><?php echo $this->_tpl_vars['calendar']; ?><?php echo '</a>'; ?><?php endif; ?><?php echo '</p></div><br clear="left" /></div>  <!-- end of Listing_header --><div class="full_listing" style="padding: 0px 10px 0px 10px;" ><p>'; ?><?php echo ((is_array($_tmp=$this->_tpl_vars['list_desclong'])) ? $this->_run_mod_handler('nl2br', true, $_tmp) : smarty_modifier_nl2br($_tmp)); ?><?php echo '</p></div>'; ?><?php if ($this->_tpl_vars['list_rows_cal'] != array ( )): ?><?php echo '<a name="Calendar"></a><h2>Events Calendar</h2>'; ?><?php $_from = $this->_tpl_vars['list_rows_cal']; if (!is_array($_from) && !is_object($_from)) { settype($_from, 'array'); }if (count($_from)):
    foreach ($_from as $this->_tpl_vars['entry']):
?><?php echo '<div  style="padding: 10px;"  '; ?><?php if ($this->_tpl_vars['entry']['moreEventLinkHref'] != ''): ?><?php echo ' onclick="location.href=\''; ?><?php echo $this->_tpl_vars['entry']['moreEventLinkHref']; ?><?php echo '\';"  style="cursor:pointer;" '; ?><?php endif; ?><?php echo '>'; ?><?php if ($this->_tpl_vars['entry']['moreEventLinkHref'] != ''): ?><?php echo '<div class="listmore" style="padding-left: 10px; margin-top: 0px; padding-top: 0px;"><a href="'; ?><?php echo $this->_tpl_vars['entry']['moreEventLinkHref']; ?><?php echo '"><img valign="top" border="0" height="25" width="25" src="/m/more.png"></a></div>'; ?><?php endif; ?><?php echo '<strong>'; ?><?php echo $this->_tpl_vars['entry']['category_name']; ?><?php echo '</strong><br />'; ?><?php if ($this->_tpl_vars['entry']['nameEvent'] != ''): ?><?php echo ''; ?><?php echo $this->_tpl_vars['entry']['nameEvent']; ?><?php echo '<br />'; ?><?php endif; ?><?php echo '<br />'; ?><?php if ($this->_tpl_vars['entry']['timesEvent'] != ''): ?><?php echo '<strong>'; ?><?php echo $this->_tpl_vars['entry']['timesEvent']; ?><?php echo '</strong><br />'; ?><?php endif; ?><?php echo ''; ?><?php echo $this->_tpl_vars['entry']['event_recurs']; ?><?php echo '<br /><br />'; ?><?php echo $this->_tpl_vars['entry']['descEvent']; ?><?php echo '<br /></div><hr />'; ?><?php endforeach; endif; unset($_from); ?><?php echo ''; ?><?php endif; ?><?php echo '</div>'; ?><?php if ($this->_tpl_vars['list_map'] != ''): ?><?php echo '<br /><H2>Location</H2><center><a href="'; ?><?php echo $this->_tpl_vars['list_mapbig']; ?><?php echo '"><img width="320" height="480" src="'; ?><?php echo $this->_tpl_vars['list_map']; ?><?php echo '" /></a></center><br />'; ?><?php endif; ?><?php echo '</div><!------- end of core ------->'; ?>

<?php $_smarty_tpl_vars = $this->_tpl_vars;
$this->_smarty_include(array('smarty_include_tpl_file' => "m10_footer.tpl", 'smarty_include_vars' => array()));
$this->_tpl_vars = $_smarty_tpl_vars;
unset($_smarty_tpl_vars);
 ?>