<?php /* Smarty version 2.6.26, created on 2012-10-10 07:43:51
         compiled from m10_Calendar_day.tpl */ ?>
<?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'config_load', 'm10_Calendar_day.tpl', 1, false),)), $this); ?>
<?php echo ''; ?><?php echo smarty_function_config_load(array('file' => "ggv_dayCal.conf"), $this);?><?php echo ''; ?><?php $_smarty_tpl_vars = $this->_tpl_vars;
$this->_smarty_include(array('smarty_include_tpl_file' => $this->_tpl_vars['headerfilename'], 'smarty_include_vars' => array()));
$this->_tpl_vars = $_smarty_tpl_vars;
unset($_smarty_tpl_vars);
 ?><?php echo '<style>'; ?><?php echo '
#menu  div {
box-align: center;
}
#menu a {
color: white;
text-decoration: none;
}
#menu ul {
margin: 0px auto 0px 10px;
padding: 0px auto 0px 10px;

}
#menu ul li {
	background-color: darkgreen;
	text-align: center;
	list-style-type: none;
	margin: 0px;
	padding: auto;
	font-size: 14px;
	font-weight: bold;
	color: white;
	float:left;
	width: 23%;
	border: 1px solid white;
}
#menu ul li a {display:block;}
'; ?><?php echo '</style><div id="main_content"><br /><div id="menu" style="height: 25px;  width: 100%;margin: 0px; padding: 0px;"><ul style="width: 90%; margin: auto; padding:10px;"><li ><a href="'; ?><?php echo $this->_tpl_vars['this_url']; ?><?php echo '&sort=time" >time</a></li><li><a href="'; ?><?php echo $this->_tpl_vars['this_url']; ?><?php echo '&sort=events" >events</a></li><li ><a href="'; ?><?php echo $this->_tpl_vars['this_url']; ?><?php echo '&sort=drinks" >drinks</a></li><li><a href="'; ?><?php echo $this->_tpl_vars['this_url']; ?><?php echo '&sort=all" >all</a></li></ul></div><!-- <h2 style="clear: both;">'; ?><?php echo $this->_tpl_vars['H1']; ?><?php echo '</h2>  --><br /><div style="text-align: center; padding: 30px 0px 10px 0px;"><a href="'; ?><?php echo $this->_tpl_vars['yesterdayHREF']; ?><?php echo '"><img style="padding-left: 0px; vertical-align: middle;" class="buttons" border="0"   src="Images/leftbutton.gif"  width="20" height="30"></a>&nbsp;<span style="font-size: 24px; font-weight: bold;">'; ?><?php echo $this->_tpl_vars['dateformatted']; ?><?php echo '</span>&nbsp;<a href="'; ?><?php echo $this->_tpl_vars['tommorrowHREF']; ?><?php echo '"><img style="padding-left: 0px; vertical-align: middle;"  class="buttons" border="0"   src="Images/rightbutton.gif" width="20" height="30"></a><br />'; ?><?php echo $this->_tpl_vars['transSunsetToday']; ?><?php echo ' '; ?><?php echo $this->_tpl_vars['sunset_today']; ?><?php echo '</div><div>'; ?><?php echo ''; ?><?php if (! ( $this->_tpl_vars['special_events'] == NULL )): ?><?php echo ''; ?><?php $this->assign('betweenListing', 'false'); ?><?php echo '<h2 style="margin: 10px 0px 0px 0px; ">'; ?><?php echo $this->_tpl_vars['transSpecialEvent']; ?><?php echo '</h2>'; ?><?php $_from = $this->_tpl_vars['special_events']; if (!is_array($_from) && !is_object($_from)) { settype($_from, 'array'); }if (count($_from)):
    foreach ($_from as $this->_tpl_vars['evnt']):
?><?php echo ''; ?><?php if ($this->_tpl_vars['betweenListing'] == 'true'): ?><?php echo '<br clear="all" /><hr style="padding: 0px 0px 0px 0px;" />'; ?><?php else: ?><?php echo ''; ?><?php $this->assign('betweenListing', 'true'); ?><?php echo ''; ?><?php endif; ?><?php echo '<div  style="padding-left: 0px; margin-top: 0px; padding-top: 10px;"   '; ?><?php if ($this->_tpl_vars['evnt']['moreEventLink'] != ''): ?><?php echo ' onclick="location.href=\''; ?><?php echo $this->_tpl_vars['evnt']['moreEventLink']; ?><?php echo '\';"  style="cursor:pointer;" '; ?><?php endif; ?><?php echo '>'; ?><?php if ($this->_tpl_vars['evnt']['moreEventLink'] != ''): ?><?php echo '<div class="listmore" style="padding-left: 10px; margin-top: 0px; padding-top: 0px;"><a href="'; ?><?php echo $this->_tpl_vars['evnt']['moreEventLink']; ?><?php echo '"><img valign="top" border="0" height="25" width="25" src="/m/more.png"></a></div>'; ?><?php endif; ?><?php echo '<span style="font-size: 14px;"><strong>&nbsp;'; ?><?php echo $this->_tpl_vars['evnt']['catnameEvent']; ?><?php echo '</strong></span><div style="padding-left: 10px; margin-top: 0px; padding-top: 0px;"><b><span class="eventdaycat">'; ?><?php echo $this->_tpl_vars['evnt']['nameEvent']; ?><?php echo '</span></b>'; ?><?php if ($this->_tpl_vars['evnt']['locationEvent'] != ''): ?><?php echo '<span class="eventdaylocation"> &nbsp;&nbsp;@ '; ?><?php echo $this->_tpl_vars['evnt']['locationEvent']; ?><?php echo '</span>'; ?><?php endif; ?><?php echo '<br />'; ?><?php if ($this->_tpl_vars['evnt']['timesEvent'] != ''): ?><?php echo '<span class="eventdaytime">'; ?><?php echo $this->_tpl_vars['evnt']['timesEvent']; ?><?php echo ' <br></span>'; ?><?php endif; ?><?php echo '<span class="eventdaydesc">'; ?><?php echo $this->_tpl_vars['evnt']['descEvent']; ?><?php echo '</span>&nbsp;</div></div>'; ?><?php endforeach; endif; unset($_from); ?><?php echo ''; ?><?php endif; ?><?php echo ''; ?><?php echo ''; ?><?php if (! ( $this->_tpl_vars['tour_events'] == NULL )): ?><?php echo ''; ?><?php $this->assign('betweenListing', 'false'); ?><?php echo '<h2 style="margin: 10px 0px 0px 0px; ">'; ?><?php echo $this->_tpl_vars['transGayToursToday']; ?><?php echo '</h2>'; ?><?php $_from = $this->_tpl_vars['tour_events']; if (!is_array($_from) && !is_object($_from)) { settype($_from, 'array'); }if (count($_from)):
    foreach ($_from as $this->_tpl_vars['evnt']):
?><?php echo ''; ?><?php if ($this->_tpl_vars['betweenListing'] == 'true'): ?><?php echo '<br clear="all" /><hr  />'; ?><?php else: ?><?php echo ''; ?><?php $this->assign('betweenListing', 'true'); ?><?php echo ''; ?><?php endif; ?><?php echo '<div  style="padding-left: 0px; margin-top: 0px; padding-top: 10px;"   '; ?><?php if ($this->_tpl_vars['evnt']['moreEventLink'] != ''): ?><?php echo ' onclick="location.href=\''; ?><?php echo $this->_tpl_vars['evnt']['moreEventLink']; ?><?php echo '\';"  style="cursor:pointer;" '; ?><?php endif; ?><?php echo '>'; ?><?php if ($this->_tpl_vars['evnt']['moreEventLink'] != ''): ?><?php echo '<div class="listmore" style="padding-left: 10px; margin-top: 0px; padding-top: 0px;"><a href="'; ?><?php echo $this->_tpl_vars['evnt']['moreEventLink']; ?><?php echo '"><img valign="top" border="0" height="25" width="25" src="/m/more.png"></a></div>'; ?><?php endif; ?><?php echo '<span style="font-size: 14px;"><strong>&nbsp;'; ?><?php echo $this->_tpl_vars['evnt']['catnameEvent']; ?><?php echo '</strong></span><div style="padding-left: 10px; margin-top: 0px; padding-top: 0px;"><b><span class="eventdaycat">'; ?><?php echo $this->_tpl_vars['evnt']['nameEvent']; ?><?php echo '</span></b>'; ?><?php if ($this->_tpl_vars['evnt']['locationEvent'] != ''): ?><?php echo '<span class="eventdaylocation"> &nbsp;&nbsp;@ '; ?><?php echo $this->_tpl_vars['evnt']['locationEvent']; ?><?php echo '</span>'; ?><?php endif; ?><?php echo '<br />'; ?><?php if ($this->_tpl_vars['evnt']['timesEvent'] != ''): ?><?php echo '<span class="eventdaytime">'; ?><?php echo $this->_tpl_vars['evnt']['timesEvent']; ?><?php echo ' <br></span>'; ?><?php endif; ?><?php echo '<span class="eventdaydesc">'; ?><?php echo $this->_tpl_vars['evnt']['descEvent']; ?><?php echo '</span>&nbsp;</div></div>'; ?><?php endforeach; endif; unset($_from); ?><?php echo ''; ?><?php endif; ?><?php echo ''; ?><?php echo ''; ?><?php if (! ( $this->_tpl_vars['today_events'] == NULL )): ?><?php echo ''; ?><?php $this->assign('betweenListing', 'false'); ?><?php echo '<h2 style="margin: 10px 0px 0px 0px; ">'; ?><?php echo $this->_tpl_vars['transEventsNoStartTime']; ?><?php echo '</h2>'; ?><?php $_from = $this->_tpl_vars['today_events']; if (!is_array($_from) && !is_object($_from)) { settype($_from, 'array'); }if (count($_from)):
    foreach ($_from as $this->_tpl_vars['evnt']):
?><?php echo ''; ?><?php if ($this->_tpl_vars['betweenListing'] == 'true'): ?><?php echo '<br clear="all" /><hr  />'; ?><?php else: ?><?php echo ''; ?><?php $this->assign('betweenListing', 'true'); ?><?php echo ''; ?><?php endif; ?><?php echo '<div  style="padding-left: 0px; margin-top: 0px; padding-top: 10px;"   '; ?><?php if ($this->_tpl_vars['evnt']['moreEventLink'] != ''): ?><?php echo ' onclick="location.href=\''; ?><?php echo $this->_tpl_vars['evnt']['moreEventLink']; ?><?php echo '\';"  style="cursor:pointer;" '; ?><?php endif; ?><?php echo '>'; ?><?php if ($this->_tpl_vars['evnt']['moreEventLink'] != ''): ?><?php echo '<div class="listmore" style="padding-left: 10px; margin-top: 0px; padding-top: 0px;"><a href="'; ?><?php echo $this->_tpl_vars['evnt']['moreEventLink']; ?><?php echo '"><img valign="top" border="0" height="25" width="25" src="/m/more.png"></a></div>'; ?><?php endif; ?><?php echo '<span style="font-size: 14px;"><strong>&nbsp;'; ?><?php echo $this->_tpl_vars['evnt']['catnameEvent']; ?><?php echo '</strong></span><div style="padding-left: 10px; margin-top: 0px; padding-top: 0px;"><b><span class="eventdaycat">'; ?><?php echo $this->_tpl_vars['evnt']['nameEvent']; ?><?php echo '</span></b>'; ?><?php if ($this->_tpl_vars['evnt']['locationEvent'] != ''): ?><?php echo '<span class="eventdaylocation"> &nbsp;&nbsp;@ '; ?><?php echo $this->_tpl_vars['evnt']['locationEvent']; ?><?php echo '</span>'; ?><?php endif; ?><?php echo '<br />'; ?><?php if ($this->_tpl_vars['evnt']['timesEvent'] != ''): ?><?php echo '<span class="eventdaytime">'; ?><?php echo $this->_tpl_vars['evnt']['timesEvent']; ?><?php echo ' <br></span>'; ?><?php endif; ?><?php echo '<span class="eventdaydesc">'; ?><?php echo $this->_tpl_vars['evnt']['descEvent']; ?><?php echo '</span>&nbsp;</div></div>'; ?><?php endforeach; endif; unset($_from); ?><?php echo ''; ?><?php endif; ?><?php echo ''; ?><?php echo ''; ?><?php if (! ( $this->_tpl_vars['events'] == NULL )): ?><?php echo ''; ?><?php $this->assign('betweenListing', 'false'); ?><?php echo '<h2  style="margin: 10px 0px 0px 0px; padding: 0px;" >'; ?><?php echo $this->_tpl_vars['transEventsByStartTime']; ?><?php echo '</h2>'; ?><?php $_from = $this->_tpl_vars['events']; if (!is_array($_from) && !is_object($_from)) { settype($_from, 'array'); }if (count($_from)):
    foreach ($_from as $this->_tpl_vars['evnt']):
?><?php echo ''; ?><?php if ($this->_tpl_vars['betweenListing'] == 'true'): ?><?php echo '<br clear="all" /><hr  />'; ?><?php else: ?><?php echo ''; ?><?php $this->assign('betweenListing', 'true'); ?><?php echo ''; ?><?php endif; ?><?php echo '<div  style="padding-left: 0px; margin-top: 0px; padding-top: 10px;"   '; ?><?php if ($this->_tpl_vars['evnt']['moreEventLink'] != ''): ?><?php echo ' onclick="location.href=\''; ?><?php echo $this->_tpl_vars['evnt']['moreEventLink']; ?><?php echo '\';"  style="cursor:pointer;" '; ?><?php endif; ?><?php echo '>'; ?><?php if ($this->_tpl_vars['evnt']['moreEventLink'] != ''): ?><?php echo '<div class="listmore" style="padding-left: 10px; margin-top: 0px; padding-top: 0px;"><a href="'; ?><?php echo $this->_tpl_vars['evnt']['moreEventLink']; ?><?php echo '"><img valign="top" border="0" height="25" width="25" src="/m/more.png"></a></div>'; ?><?php endif; ?><?php echo '<span style="font-size: 14px;"><strong>&nbsp;'; ?><?php echo $this->_tpl_vars['evnt']['catnameEvent']; ?><?php echo '</strong></span><div style="padding-left: 10px; margin-top: 0px; padding-top: 0px;"><b><span class="eventdaycat">'; ?><?php echo $this->_tpl_vars['evnt']['nameEvent']; ?><?php echo '</span></b>'; ?><?php if ($this->_tpl_vars['evnt']['locationEvent'] != ''): ?><?php echo '<span class="eventdaylocation"> &nbsp;&nbsp;@ '; ?><?php echo $this->_tpl_vars['evnt']['locationEvent']; ?><?php echo '</span>'; ?><?php endif; ?><?php echo '<br />'; ?><?php if ($this->_tpl_vars['evnt']['timesEvent'] != ''): ?><?php echo '<span class="eventdaytime">'; ?><?php echo $this->_tpl_vars['evnt']['timesEvent']; ?><?php echo ' <br></span>'; ?><?php endif; ?><?php echo '<span class="eventdaydesc">'; ?><?php echo $this->_tpl_vars['evnt']['descEvent']; ?><?php echo '</span>&nbsp;</div></div>'; ?><?php endforeach; endif; unset($_from); ?><?php echo ''; ?><?php endif; ?><?php echo ''; ?><?php echo ''; ?><?php if (! ( $this->_tpl_vars['bars_events'] == NULL )): ?><?php echo ''; ?><?php $this->assign('betweenListing', 'false'); ?><?php echo '<h2  style="margin: 10px 0px 0px 0px; padding: 0px;" >'; ?><?php echo $this->_tpl_vars['transBarSpecialsToday']; ?><?php echo '</h2>'; ?><?php $_from = $this->_tpl_vars['bars_events']; if (!is_array($_from) && !is_object($_from)) { settype($_from, 'array'); }if (count($_from)):
    foreach ($_from as $this->_tpl_vars['evnt']):
?><?php echo ''; ?><?php if ($this->_tpl_vars['betweenListing'] == 'true'): ?><?php echo '<br clear="all" /><hr  />'; ?><?php else: ?><?php echo ''; ?><?php $this->assign('betweenListing', 'true'); ?><?php echo ''; ?><?php endif; ?><?php echo '<div  style="padding-left: 0px; margin-top: 0px; padding-top: 10px;"   '; ?><?php if ($this->_tpl_vars['evnt']['moreEventLink'] != ''): ?><?php echo ' onclick="location.href=\''; ?><?php echo $this->_tpl_vars['evnt']['moreEventLink']; ?><?php echo '\';"  style="cursor:pointer;" '; ?><?php endif; ?><?php echo '>'; ?><?php if ($this->_tpl_vars['evnt']['moreEventLink'] != ''): ?><?php echo '<div class="listmore" style="padding-left: 10px; margin-top: 0px; padding-top: 0px;"><a href="'; ?><?php echo $this->_tpl_vars['evnt']['moreEventLink']; ?><?php echo '"><img valign="top" border="0" height="25" width="25" src="/m/more.png"></a></div>'; ?><?php endif; ?><?php echo '<span style="font-size: 14px;"><strong>&nbsp;'; ?><?php echo $this->_tpl_vars['evnt']['catnameEvent']; ?><?php echo '</strong></span><div style="padding-left: 10px; margin-top: 0px; padding-top: 0px;"><b><span class="eventdaycat">'; ?><?php echo $this->_tpl_vars['evnt']['nameEvent']; ?><?php echo '</span></b>'; ?><?php if ($this->_tpl_vars['evnt']['locationEvent'] != ''): ?><?php echo '<span class="eventdaylocation"> &nbsp;&nbsp;@ '; ?><?php echo $this->_tpl_vars['evnt']['locationEvent']; ?><?php echo '</span>'; ?><?php endif; ?><?php echo '<br />'; ?><?php if ($this->_tpl_vars['evnt']['timesEvent'] != ''): ?><?php echo '<span class="eventdaytime">'; ?><?php echo $this->_tpl_vars['evnt']['timesEvent']; ?><?php echo ' <br></span>'; ?><?php endif; ?><?php echo '<span class="eventdaydesc">'; ?><?php echo $this->_tpl_vars['evnt']['descEvent']; ?><?php echo '</span>&nbsp;</div></div>'; ?><?php endforeach; endif; unset($_from); ?><?php echo ''; ?><?php endif; ?><?php echo ''; ?><?php echo ''; ?><?php if (! ( $this->_tpl_vars['happy_events'] == NULL )): ?><?php echo ''; ?><?php $this->assign('betweenListing', 'false'); ?><?php echo '<h2  style="margin: 10px 0px 0px 0px; padding: 0px;" >'; ?><?php echo $this->_tpl_vars['transHappyHoursToday']; ?><?php echo '</h2>'; ?><?php $_from = $this->_tpl_vars['happy_events']; if (!is_array($_from) && !is_object($_from)) { settype($_from, 'array'); }if (count($_from)):
    foreach ($_from as $this->_tpl_vars['evnt']):
?><?php echo ''; ?><?php if ($this->_tpl_vars['betweenListing'] == 'true'): ?><?php echo '<br clear="all" /><hr  />'; ?><?php else: ?><?php echo ''; ?><?php $this->assign('betweenListing', 'true'); ?><?php echo ''; ?><?php endif; ?><?php echo '<div  style="padding-left: 0px; margin-top: 0px; padding-top: 10px;"   '; ?><?php if ($this->_tpl_vars['evnt']['moreEventLink'] != ''): ?><?php echo ' onclick="location.href=\''; ?><?php echo $this->_tpl_vars['evnt']['moreEventLink']; ?><?php echo '\';"  style="cursor:pointer;" '; ?><?php endif; ?><?php echo '>'; ?><?php if ($this->_tpl_vars['evnt']['moreEventLink'] != ''): ?><?php echo '<div class="listmore" style="padding-left: 10px; margin-top: 0px; padding-top: 0px;"><a href="'; ?><?php echo $this->_tpl_vars['evnt']['moreEventLink']; ?><?php echo '"><img valign="top" border="0" height="25" width="25" src="/m/more.png"></a></div>'; ?><?php endif; ?><?php echo '<span style="font-size: 14px;"><strong>&nbsp;'; ?><?php echo $this->_tpl_vars['evnt']['catnameEvent']; ?><?php echo '</strong></span><div style="padding-left: 10px; margin-top: 0px; padding-top: 0px;"><b><span class="eventdaycat">'; ?><?php echo $this->_tpl_vars['evnt']['nameEvent']; ?><?php echo '</span></b>'; ?><?php if ($this->_tpl_vars['evnt']['locationEvent'] != ''): ?><?php echo '<span class="eventdaylocation"> &nbsp;&nbsp;@ '; ?><?php echo $this->_tpl_vars['evnt']['locationEvent']; ?><?php echo '</span>'; ?><?php endif; ?><?php echo '<br />'; ?><?php if ($this->_tpl_vars['evnt']['timesEvent'] != ''): ?><?php echo '<span class="eventdaytime">'; ?><?php echo $this->_tpl_vars['evnt']['timesEvent']; ?><?php echo ' <br></span>'; ?><?php endif; ?><?php echo '<span class="eventdaydesc">'; ?><?php echo $this->_tpl_vars['evnt']['descEvent']; ?><?php echo '</span>&nbsp;</div></div>'; ?><?php endforeach; endif; unset($_from); ?><?php echo ''; ?><?php endif; ?><?php echo ''; ?><?php echo ''; ?><?php if (! ( $this->_tpl_vars['restaurant_events'] == NULL )): ?><?php echo ''; ?><?php $this->assign('betweenListing', 'false'); ?><?php echo '<h2  style="margin: 10px 0px 0px 0px; padding: 0px;" >'; ?><?php echo $this->_tpl_vars['transRestSpecialsToday']; ?><?php echo '</h2>'; ?><?php $_from = $this->_tpl_vars['restaurant_events']; if (!is_array($_from) && !is_object($_from)) { settype($_from, 'array'); }if (count($_from)):
    foreach ($_from as $this->_tpl_vars['evnt']):
?><?php echo ''; ?><?php if ($this->_tpl_vars['betweenListing'] == 'true'): ?><?php echo '<br clear="all" /><hr  />'; ?><?php else: ?><?php echo ''; ?><?php $this->assign('betweenListing', 'true'); ?><?php echo ''; ?><?php endif; ?><?php echo '<div  style="padding-left: 0px; margin-top: 0px; padding-top: 10px;"   '; ?><?php if ($this->_tpl_vars['evnt']['moreEventLink'] != ''): ?><?php echo ' onclick="location.href=\''; ?><?php echo $this->_tpl_vars['evnt']['moreEventLink']; ?><?php echo '\';"  style="cursor:pointer;" '; ?><?php endif; ?><?php echo '>'; ?><?php if ($this->_tpl_vars['evnt']['moreEventLink'] != ''): ?><?php echo '<div class="listmore" style="padding-left: 10px; margin-top: 0px; padding-top: 0px;"><a href="'; ?><?php echo $this->_tpl_vars['evnt']['moreEventLink']; ?><?php echo '"><img valign="top" border="0" height="25" width="25" src="/m/more.png"></a></div>'; ?><?php endif; ?><?php echo '<span style="font-size: 14px;"><strong>&nbsp;'; ?><?php echo $this->_tpl_vars['evnt']['catnameEvent']; ?><?php echo '</strong></span><div style="padding-left: 10px; margin-top: 0px; padding-top: 0px;"><b><span class="eventdaycat">'; ?><?php echo $this->_tpl_vars['evnt']['nameEvent']; ?><?php echo '</span></b>'; ?><?php if ($this->_tpl_vars['evnt']['locationEvent'] != ''): ?><?php echo '<span class="eventdaylocation"> &nbsp;&nbsp;@ '; ?><?php echo $this->_tpl_vars['evnt']['locationEvent']; ?><?php echo '</span>'; ?><?php endif; ?><?php echo '<br />'; ?><?php if ($this->_tpl_vars['evnt']['timesEvent'] != ''): ?><?php echo '<span class="eventdaytime">'; ?><?php echo $this->_tpl_vars['evnt']['timesEvent']; ?><?php echo ' <br></span>'; ?><?php endif; ?><?php echo '<span class="eventdaydesc">'; ?><?php echo $this->_tpl_vars['evnt']['descEvent']; ?><?php echo '</span>&nbsp;</div></div>'; ?><?php endforeach; endif; unset($_from); ?><?php echo ''; ?><?php endif; ?><?php echo ''; ?><?php if (false && ! ( $this->_tpl_vars['closed_list'] == NULL )): ?><?php echo '<h2>'; ?><?php echo $this->_tpl_vars['transClosedToday']; ?><?php echo '</h2>'; ?><?php $_from = $this->_tpl_vars['closed_list']; if (!is_array($_from) && !is_object($_from)) { settype($_from, 'array'); }if (count($_from)):
    foreach ($_from as $this->_tpl_vars['evnt']):
?><?php echo '<div  style="padding-left: 15px;">'; ?><?php if ($this->_tpl_vars['evnt']['moreEventLink'] != ''): ?><?php echo '<div class="listmore"><a href="'; ?><?php echo $this->_tpl_vars['evnt']['moreEventLink']; ?><?php echo '"><img border="0" height="25" width="25" src="/m/more.png"></a></div>'; ?><?php endif; ?><?php echo '<b><span class="eventdaycat">'; ?><?php echo $this->_tpl_vars['evnt']['nameEvent']; ?><?php echo '</span></b>'; ?><?php if ($this->_tpl_vars['evnt']['locationEvent'] != ''): ?><?php echo '<span class="eventdaylocation"> &nbsp;&nbsp;@ '; ?><?php echo $this->_tpl_vars['evnt']['locationEvent']; ?><?php echo '</span>'; ?><?php endif; ?><?php echo '<br />'; ?><?php if ($this->_tpl_vars['evnt']['timesEvent'] != ''): ?><?php echo '<span class="eventdaytime">'; ?><?php echo $this->_tpl_vars['evnt']['timesEvent']; ?><?php echo ' <br></span>'; ?><?php endif; ?><?php echo '<span class="eventdaydesc">'; ?><?php echo $this->_tpl_vars['evnt']['descEvent']; ?><?php echo '</span>&nbsp;</div><hr />'; ?><?php endforeach; endif; unset($_from); ?><?php echo ''; ?><?php endif; ?><?php echo '</div></div>'; ?><?php $_smarty_tpl_vars = $this->_tpl_vars;
$this->_smarty_include(array('smarty_include_tpl_file' => "m10_footer.tpl", 'smarty_include_vars' => array()));
$this->_tpl_vars = $_smarty_tpl_vars;
unset($_smarty_tpl_vars);
 ?><?php echo ''; ?>